# Desarrollo de la aplicaci√≥n con Gradio

In [1]:
# load the dataset from pycaret
from pycaret.datasets import get_data
data = get_data('insurance')

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [2]:
# initialize setup
from pycaret.regression  import *
s = setup(data, target = 'charges',
    session_id = 123,
         silent = True)

In [3]:
# train model
best = compare_models()

###

In [4]:
def predict_charges(age, bmi,sex,smoker,region,children):
    df = pd.DataFrame.from_dict({'sex': [sex], 'age': [age], 'smoker': [smoker],'bmi':[bmi],'region':[region],'children':[children]})
    
    pred = predict_model(best, df)['Label'][0]
    
    #df = encode_attributes(df)
    #pred = blend_saved.predict(df).tolist()[0]
    return 'Cargos sanitarios : '+str(pred)

In [6]:
import gradio as gr

sex = gr.inputs.Radio(['female', 'male'], label='sex')
smoker = gr.inputs.Radio(['no', 'yes'], label='smoker')
children = gr.inputs.Radio([2, 3, 1, 4, 5, 0], label='children')
region = gr.inputs.Radio(['northeast', 'southeast', 'northwest', 'southwest'], 
                         label='region')

age = gr.inputs.Slider(minimum=15, maximum=75, default=16, label='age')
bmi = gr.inputs.Slider(minimum=15, maximum=60, default=16, label='bmi')

In [7]:
gr.Interface(predict_charges, inputs=[age, bmi,sex,smoker,region,children], 
             outputs='label',
             title='Medical Insurance Cost Prediction',
             capture_session=True,
             live=True).launch();

Running on local URL:  http://127.0.0.1:7860/

To create a public link, set `share=True` in `launch()`.